// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.EdIlyin.Http")>]
[<assembly: AssemblyProductAttribute("FSharp.EdIlyin.Http")>]
[<assembly: AssemblyDescriptionAttribute("Project has no summmary; update build.fsx")>]
[<assembly: AssemblyVersionAttribute("1.1.2")>]
[<assembly: AssemblyFileVersionAttribute("1.1.2")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.EdIlyin.Http"
    let [<Literal>] AssemblyProduct = "FSharp.EdIlyin.Http"
    let [<Literal>] AssemblyDescription = "Project has no summmary; update build.fsx"
    let [<Literal>] AssemblyVersion = "1.1.2"
    let [<Literal>] AssemblyFileVersion = "1.1.2"
    let [<Literal>] AssemblyConfiguration = "Release"
